# Cantidad de vacantes por posición
VACANTES_GOLPEADORES = 1
VACANTES_CAZADORES = 1
VACANTES_BUSCADORES = 1

# Rango de atributos Buscador
NERVIOSISMO_BUSCADOR_MIN = 5
NERVIOSISMO_BUSCADOR_MAX = 20
VELOCIDAD_BUSCADOR_MIN = 10
VELOCIDAD_BUSCADOR_MAX = 25
EQUILIBRIO_BUSCADOR_MIN = 2
EQUILIBRIO_BUSCADOR_MAX = 15

# Rango de atributos Golpeador
NERVIOSISMO_GOLPEADOR_MIN = 5
NERVIOSISMO_GOLPEADOR_MAX = 15
VELOCIDAD_GOLPEADOR_MIN = 5
VELOCIDAD_GOLPEADOR_MAX = 20
EQUILIBRIO_GOLPEADOR_MIN = 5
EQUILIBRIO_GOLPEADOR_MAX = 20

# Rango de atributos Cazador
NERVIOSISMO_CAZADOR_MIN = 10
NERVIOSISMO_CAZADOR_MAX = 25
VELOCIDAD_CAZADOR_MIN = 15
VELOCIDAD_CAZADOR_MAX = 30
EQUILIBRIO_CAZADOR_MIN = 5
EQUILIBRIO_CAZADOR_MAX = 15

# Probabilidades de acciones Estudiante
PROBABILIDAD_APLAUDIR_GRYFFINDOR = 0.8
PROBABILIDAD_APLAUDIR_SLYTHERIN = 0.3
PROBABILIDAD_ABUCHEAR_GRYFFINDOR = 0.2
PROBABILIDAD_ABUCHEAR_SLYTHERIN = 0.9

# Ponderadores para cada Posicion
PONDERADOR_VELOCIDAD_BUSCADOR = 2
PONDERADOR_EQUILIBRIO_BUSCADOR = 0.5
PONDERADOR_NERVIOSISMO_BUSCADOR = 1.5
PONDERADOR_VELOCIDAD_GOLPEADOR = 0.5
PONDERADOR_EQUILIBRIO_GOLPEADOR = 1.5
PONDERADOR_NERVIOSISMO_GOLPEADOR = 2
PONDERADOR_VELOCIDAD_CAZADOR = 2.5
PONDERADOR_EQUILIBRIO_CAZADOR = 0.5
PONDERADOR_NERVIOSISMO_CAZADOR = 1

# Bonos por casa
BONOS_CASA = {
    'MIN_VALOR_GRYFFINDOR': 0,
    'MAX_VALOR_GRYFFINDOR': 10,
    'MIN_AMBICION_SLYTHERIN': 0,
    'MAX_AMBICION_SLYTHERIN': 12
}
